name: Antal János Monori
bio: Kickass mobile developer living and working in Denmark 🇩🇰
description: A playground of nerd who likes oversharing and speaking his mind out

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.png

url: https://monori.me

permalink: /:title/

show_drafts: true
future: false

markdown: kramdown
highlighter: rouge

# if you don't have any of social below, comment the line
twitter: anthonymonori
linkedin: anthonymonori
github: anthonymonori
stackoverflow: 2759296/anthonymonori
email: anthony@monori.me

authors:
    anthonymonori:
        name: Antal János Monori
        bio: Kickass Android developer living and working in Denmark 🇩🇰
        external-image: false
        picture: assets/images/profile.png
        twitter: anthonymonori

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# enable maps support using the jekyll-maps plugin
maps:
  google:
    api_key: AIzaSyAm9Qr58HPVVr2FJ_Co7y5jb_Zz1jgZt-g

projects: true
about: true
blog: true

read-time: true
show-tags: false
related: true
blog-nav-links: false
show-author: true
animation: false

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-youtube
  - jekyll-maps

jekyll-mentions:
    base_url: https://twitter.com
