name: Antal János Monori
bio: Senior software engineer @Skyscanner | Previously at LEGO
description: Thoughts about crafting good code and making great coffee ☕️

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: https://monori.me

permalink: /:title/

show_drafts: false
future: false

markdown: kramdown
highlighter: rouge

# if you don't have any of social below, comment the line
twitter: hifromantal
linkedin: hifromantal
github: anthonymonori
stackoverflow: 2759296/anthonymonori
email: anthonymonori@gmail.com

authors:
    anthonymonori:
        name: Antal János Monori
        bio: Senior software engineer @Skyscanner | Previously at LEGO
        external-image: false
        picture: assets/images/profile.jpg
        twitter: hifromantal

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

projects: true
about: true
blog: true

read-time: true
show-tags: false
related: true
blog-nav-links: false
show-author: true
animation: false

sass:
    sass_dir: _sass
    style: :compressed

plugins:
    - jemoji
    - jekyll-mentions
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-paginate
    - jekyll-youtube
    - jekyll-redirect-from 

jekyll-mentions:
    base_url: https://twitter.com
