version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      
      - run:
        name: "Install dependencies"
        command: |
            gem install bundler jekyll |
            bundle install |
            brew install yarn |
            yarn install

      - name: "Build"
        command: jekyll build
      
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: Deploy Master to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN