name: Deploy

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: GHA Jekyll Build
      uses: gha-utilities/jekyll-build@v0.0.1
    - name: Firebase Deploy
      uses: jakejarvis/firebase-deploy-action@v0.1.0
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
